name: Builds

on:
  push:
    branches: [master] # Just in case master was not up to date while merging PR
  pull_request:
    types: [opened, synchronize]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Archiving
        run: cd Archiving && ./gradlew app:assembleRelease && cd ..

      - name: Basic-Video-Chat
        run: cd Basic-Video-Chat && ./gradlew app:assembleRelease && cd ..

      - name: Custom-Audio-Driver
        run: cd Custom-Audio-Driver && ./gradlew app:assembleRelease && cd ..

      - name: Custom-Video-Driver
        run: cd Custom-Video-Driver && ./gradlew app:assembleRelease && cd ..

      - name: FrameMetadata
        run: cd FrameMetadata && ./gradlew app:assembleRelease && cd ..

      - name: Multiparty-ConstraintLayout
        run: cd Multiparty-ConstraintLayout && ./gradlew app:assembleRelease && cd ..

      - name: PictureInPicture
        run: cd PictureInPicture && ./gradlew app:assembleRelease && cd ..

      - name: Screen-Sharing
        run: cd Screen-Sharing && ./gradlew app:assembleRelease && cd ..

      - name: Signaling
        run: cd Signaling && ./gradlew app:assembleRelease && cd ..

      - name: Simple-Multiparty
        run: cd Simple-Multiparty && ./gradlew app:assembleRelease && cd ..

      
